### ISSUE TITLE
CSV export of expression values not working

### ISSUE THREAD

**Issue by lsterck** [thpar/zmarina#6]
when clicked opens a page not found error page

**Comment by thpar** [comment]
Can you provide steps to reproduce?
For me:
 - Click gene name in exImage
 - Click button Expression Values
 - Values and CSV button pop up
 - Click CSV button >> small plain text file gets downloaded

**Comment by lsterck** [comment]
Ok, Same steps do might be a browser issue ( edge ) ?

L.

 Lieven Sterck - Senior Postdoctoral Scientist
 BioinformaticsVIB-UGent Center for Plant Systems Biology
 Ghent University
 Technologiepark 927 - 9052 Ghent - Belgium
 Tel. +32(0)9 331 38 21
 www.psb.ugent.be
"Facts are meaningless. You could use facts to prove anything that&#39;s even remotely true"   - H. Simpson

**Comment by lsterck** [comment]
butt ugly file name but seems to work in FF indeed. So it's a browser issue

**Comment by thpar** [comment]
Browser check was relying on `navigator.appName`, for which every browser (including IE) now returns 'Netscape'

**Comment by thpar** [comment]
Still not working in IE

**Comment by lsterck** [comment]
now no error anymore in Edge but no results either ???

**Comment by thpar** [comment]
Yeah... Edge apparently gives a console error:
```
Access is denied
```
for the `click()` function.

Didn't find a solution so far, so for now, just stop using Edge.

**Comment by lsterck** [comment]
ok :(
but my laptop does edge automatically :-p

**Comment by thpar** [comment]
Related:
https://stackoverflow.com/questions/27463901/setting-window-location-or-window-open-in-angularjs-gives-access-is-denied-in

**Comment by thpar** [comment]
```

**Comment by thpar** [comment]
Surprise...
> It looks like IE blocks window.open on blobs, but implemented their own functions

Worth a try:
```
if (window.navigator && window.navigator.msSaveOrOpenBlob) {
    window.navigator.msSaveOrOpenBlob(blob);
}
else {
    var objectUrl = URL.createObjectURL(blob);
    window.open(objectUrl);
}
```
