### ISSUE TITLE
Figure download/export works but displays wrong url address 

### ISSUE THREAD

**Issue by lsterck** [thpar/zmarina#7]
it asks what you want to do with download. 
but it says from: spruce.plantphys.umu.se  ; which doesn't seem right ;)

**Comment by thpar** [comment]
It actually is correct: the download script runs at http://spruce.plantphys.umu.se/cDNAeFP/download.pl  
We should install it locally.
@irusri could provide us with a link to or a copy of the code?

**Comment by thpar** [comment]
It might be cleaner to replace Perl by PHP and use `php-tcpdf` (pdf) and `php-pecl-imagick` (png)

**Comment by irusri** [comment]
That would be great if we can find some good alternative to Perl script. [Here](https://github.com/irusri/zmarina/blob/master/download.pl) is the current script.

**Comment by thpar** [comment]
Tested and approved.
Using the same tool (`rsvg-convert`) as the Perl script, but simply calling it from PHP.
